Add ability to toggle background colors for image previews
FLEXTool/FLEX pull request #494
Opened 2020-12-15 00:49 UTC by matrush

The default pattern background doesn't work well for some of the transparent images, adding this tap to toggle gesture can greatly improve the usability.

The 3 colors combination should work pretty well for most of the cases.

![Change Color](https://user-images.githubusercontent.com/627231/102153496-30043f80-3e2c-11eb-8111-694f5bc80b4e.gif)

2020-12-15 00:57 UTC, NSExceptional requested changes
I was just thinking about this the other day when I was looking at your last PR! Nice work!

I'm gonna push a few minor changes (rename a few things, remove the whitespace changes, etc) then we're good to go!

2020-12-15 00:57 UTC, NSExceptional commented
Oops, this is your own fork, unlike the last PR; so I should ask, do you mind if I make some changes myself to your branch?

2020-12-15 02:40 UTC, matrush commented
> Oops, this is your own fork, unlike the last PR; so I should ask, do you mind if I make some changes myself to your branch?

Yeah totally okay, feel free to make changes!

2020-12-16 00:35 UTC, NSExceptional approved these changes

2020-12-16 00:35 UTC, merged